### ISSUE TITLE
Export directory issue when syncing packagage for Qfield

### ISSUE THREAD

**Issue by bakkerss** [opengisch/QField#1003]
I have installed the Qfield sync plugin.

Under 'preferences' you can define a default import and export directory.

When you press the button 'Package for Qfield' a window appears with the default directories set in the preferences  extended with the file name of the project. For example:

C:\Users\User\OneDrive\Qfield\Export\Filename

A problem occurs if you repeat this procedure. The first path determoned in the first step is extended again with the filename

C:\Users\User\OneDrive\Qfield\Export\Filename\Filename

This goes on and on untill the filename exceeds the maximum file length.

### Reproduction Steps:

See description above

### Expected behavior:

When syncing the default directory should be extended only once with the filename.

[Describe expected behavior here]

### Observed behavior:

See description above

### Screenshots and GIFs

**QField version:** 

QGIS-versie | 3.12.2-București | QGIS code revisie | 8a1fb33634
-- | -- | -- | --
Gecompileerd tegen Qt | 5.11.2 | Gebruikt nu Qt | 5.11.2
Gecompileerd tegen GDAL/OGR | 3.0.4 | Gebruikt nu GDAL/OGR | 3.0.4
Gecompileerd tegen GEOS | 3.8.1-CAPI-1.13.3 | Gebruikt nu GEOS | 3.8.1-CAPI-1.13.3
Gecompileerd tegen SQLite | 3.29.0 | Uitgevoerd met SQLite | 3.29.0
PostgreSQL Client Versie | 11.5 | SpatiaLite-versie | 4.3.0
QWT versie | 6.1.3 | QScintilla2 Versie | 2.10.8
Gecompileerd tegen PROJ | 6.3.1 | Gebruikt nu PROJ | Rel. 6.3.1, February 10th, 2020
Versie OS | Windows 10 (10.0)
Actieve plug-ins van Python | GeoCoding; inspireNL; mmqgis; OSMDownloader; pdokservicesplugin; pdok_locatieserver_locator_filter; qfieldsync; QuickOSM; quick_map_services; db_manager; MetaSearch; processing

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by saemiw** [comment]
I think this has been fixed recently: https://github.com/opengisch/qfieldsync/pull/144 
@3nids can you confirm (or push the fix to the plugin repository)?

**Comment by shapley** [comment]
This issue is still a problem using Ubuntu 20.04 with QGIS 3.22. Has there been a fix?
