### ISSUE TITLE
@position_horizontal_accuracy not recorded in QField 1.8

### ISSUE THREAD

**Issue by she-weeds** [opengisch/QField#1580]
I can't seem to log horizontal accuracy in the data using the @position_horizontal_accuracy variable in QField 1.8.0. Projects where it worked on 1.7.8 no longer record anything in 1.8.0. This is for projects set up in QGIS 3.16.1

### Reproduction Steps:

1. Set a field to have a default value of @position_horizontal_accuracy
2. Enable GPS and digitise feature
3. Horizontal accuracy field remains NULL

### Expected behavior:

Should record horizontal accuracy in field

### Observed behavior:

FIeld values remain NULL

### Screenshots and GIFs

See attached mp4

https://user-images.githubusercontent.com/41975056/103820440-7dd53600-50c0-11eb-9ffd-82c07356191c.mp4

**QField version:** 1.8.0 - from Google Play

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by signedav** [comment]
Can you test with the latest beta release 1.8.1? Thanks a lot.

**Comment by she-weeds** [comment]
Hi, it still shows a null value with 1.8.1. Love the position accuracy badge although the enforce accuracy requirements doesn't seem to prevent me recording features with bad accuracy (yet).

I should note I have tested this out on a OnePlus 5 and a Galaxy Tab A 2018, both using internal and external gps.

**Comment by stevenmizuno** [comment]
I have found that with Internal device all @position_... variables return null values. 

If I use a Bluetooth connected GPS most of variables return non-null values. One variable returns null: `@position_source_name`. Two variables return empty strings: `@position_coordinate` and `@position_used_satelites`.

I looked at src/core/expressioncontextutils.cpp to check for correct variable names and found more than I had seen in documentation. Note that `@hdop` really should be `@position_hdop` to be consistent and that satellite is misspelled (one 'l') in two variables.

This is what I used as the default value on a point layer to get the results:
`'src name: ' || coalesce(@position_source_name,'?') 
|| '  time of fix: ' || coalesce(@position_timestamp,'?') 
|| '  position: ' || coalesce(@position_coordinate,'?') 
|| '  Ground speed: ' || coalesce(@position_ground_speed,'?') 
|| '  V spd: ' || coalesce(@position_vertical_speed,'?')  
|| '  direction: ' || coalesce(@position_direction,'?') 
|| '  mag var: ' || coalesce(@position_magnetic_variation,'') 
|| '  num used sats: ' || coalesce(@position_number_of_used_satelites,'?') 
|| '  used sats: ' || coalesce(@position_used_satelites,'?') 
|| '  fix stat: '|| coalesce(@position_fixstatus_description,'?') 
|| '  qual: ' || coalesce(@position_quality_description,'?') 
|| '  fix mode: ' || coalesce(@position_fix_mode,'?') 
|| '  h v p -dop: ' ||coalesce(@hdop,'?') || '  ' || coalesce(@position_vdop,'?') || '  ' || coalesce(@position_pdop,'?') 
|| '  h v -acc: ' || coalesce(@position_horizontal_accuracy,'?') || '  ' || coalesce(@position_vertical_accuracy,'?') 
`

using QField PR1576 (essentially 1.8.1) the results:
[Internal]
src name: ?  time of fix: ?  position: ?  Ground speed: ?  V spd: ?  direction: ?  mag var: ?  num used sats: ?  used sats: ?  fix stat: ?  qual: ?  fix mode: ?  h v p -dop: ?  ?  ?  h v -acc: ?  ?

[Bluetooth connected GPS]
src name: ?  time of fix: 2021-01-07T21:34:52.000Z  position:  Ground speed: 0.0926  V spd: nan  direction: 338.35  mag var: nan  num used  sats: 7  used sats:  fix stat:  Fix3D  qual: DGPS  fix mode: A  h v p -dop: 1.6  4.3  4.6  h v -acc: 4.1436698710201325  15.5

I believe that `@position_source_name` should return the GNSS device name as shown in Position settings.

**Comment by m-kuhn** [comment]
Thank you for these remarks.

A fix has been proposed in #1585.

@stevenmizuno the position_coordinate is a point, use `x(@position_coordinate)` and similar functions to extract the content. `@position_used_satellites` (spelling fixed in #1585) is an array, use expression functions for arrays to get access. Documentation for these details would be much required.

Another note, just because you have proven to be able to explore the code on github, feel free to directly propose spelling fixes (there's an edit button on top of each file, changes will still need to be reviewed in pull requests, no risk to destroy anything).

**Comment by Benwaa74** [comment]
@m-kuhn 
It appears this is still occurring or it has crept back in...

Using either 1.8.1 or a recent PR build "PR1625"(faecde), and the same expression (see below) as @stevenmizuno (with the addition of x, y and z positions at the end) as the Default value of a text field, I get only question-marks in the field.

I am connecting to a Emlid Reach RS2 antenna via Bluetooth, using the NMEA string. The connection is fine and I receive a nice accurate position (connecting to a CORS network for corrections). However, I need to be able to record the x, y and z positions of points collected and I cannot get this to work. I have tried with both the internal device and the reach device but still no luck.

Expression:
'src name: ' || coalesce(@position_source_name,'?') || ' time of fix: ' || coalesce(@position_timestamp,'?') || ' position: ' || coalesce(@position_coordinate,'?') || ' Ground speed: ' || coalesce(@position_ground_speed,'?') || ' V spd: ' || coalesce(@position_vertical_speed,'?') || ' direction: ' || coalesce(@position_direction,'?') || ' mag var: ' || coalesce(@position_magnetic_variation,'') || ' num used sats: ' || coalesce(@position_number_of_used_satelites,'?') || ' used sats: ' || coalesce(@position_used_satelites,'?') || ' fix stat: '|| coalesce(@position_fixstatus_description,'?') || ' qual: ' || coalesce(@position_quality_description,'?') || ' fix mode: ' || coalesce(@position_fix_mode,'?') || ' h v p -dop: ' ||coalesce(@hdop,'?') || ' ' || coalesce(@position_vdop,'?') || ' ' || coalesce(@position_pdop,'?') || ' h v -acc: ' || coalesce(@position_horizontal_accuracy,'?') || ' ' || coalesce(@position_vertical_accuracy,'?') || ' x-position: ' || coalesce(x(@position_coordinate),'?') || ' y-position: ' || coalesce(y(@position_coordinate),'?') || ' z-position: ' || coalesce(z(@position_coordinate),'?')

Result:
src name: ? time of fix: ? position: ? Ground speed: ? V spd: ? direction: ? mag var: ? num used sats: ? used sats: ? fix stat: ? qual: ? fix mode: ? h v p -dop: ? ? ? h v -acc: ? ? x-position: ? y-position: ? z-position: ?

I have tried with and without the 'coalesce' function and also individually eg, x(@position_coordinate). But I get nothing in the form field (only Null or ?)

Am I doing something wrong or should this work?

I can get the positions to record if I use the expression: "x($geometry)" [without the quotes of course] but this returns an error in the Message Logs which says: "Default value expression for Control_Checks:Easting has evaluation error. Cannot convert to geometry". It still records the correct value in the field but not convinced it's the correct way to achieve this.

Any help appreciated.

Regards,

Ben
