### ISSUE TITLE
WMS does not work?

### ISSUE THREAD

**Issue by giedrioks26** [opengisch/QField#19]
The project does not work with a WMS layer. When you open only visible white sheet. Sony xperia tabletZ1, Android 4.3

**Comment by boesiii** [comment]
I wonder if it is similar to issue 13

**Comment by m-kuhn** [comment]
Is this still an issue with the latest release?

**Comment by boesiii** [comment]
Yes this is still an issue.

My Qgis map projection is epsg 2272.  The shapefiles displya correctly in qfield but the WMS layer does not show up.  The WMS layer is also epsg 2272.  Let me know if you need any other information.

**Comment by m-kuhn** [comment]
It works here. Maybe a problem with login credentials, VPN, ...?

**Comment by giedrioks26** [comment]
It still does not work.
My Qgis map projection is epsg 3346

**Comment by m-kuhn** [comment]
is somebody able to provide a demo project?

**Comment by boesiii** [comment]
Working on it now

**Comment by boesiii** [comment]
Below is a sample project with one shapefile layer and one WMS layer.  Both layers are 4326 projection.

[parcels_4326.zip](https://github.com/opengisch/QField/files/186298/parcels_4326.zip)

**Comment by m-kuhn** [comment]
Opening the project on QGIS with Qt5 (Desktop) prints:

```
2016-03-29T12:28:17	1	Map request error (Title:Service Exception; Error:StylesNotDefined (Unknown error code)
			The WMS vendor also reported: 
			Parameter 'styles' is required.
			  ; URL: http://data1.commons.psu.edu/arcgis/services/pasda/AlleghenyCountyImagery2013/MapServer/WMSServer?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=-80.0314826540908939,40.42334773038854223,-79.97368070741191559,40.4598866608862977&CRS=CRS:84&WIDTH=1313&HEIGHT=830&LAYERS=0&STYLES&FORMAT=image/jpeg&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96)
```

**Comment by m-kuhn** [comment]
Fixed upstream https://github.com/qgis/QGIS/commit/631a7fd9d3b72b8563b19d60e88de370028d1b44 will be part of release 0.5.4

**Comment by giedrioks26** [comment]
WMS is still not working. Reference to project with WMS https://drive.google.com/open?id=0BzfwITizxXObRDcxYnVzZ3U0T3c

**Comment by m-kuhn** [comment]
Looks like an SSL issue. I guess https is involved at some stage.

Maybe it just needs packaging openssl.

```
W QField  : (null):0 ((null)): qt.network.ssl: QSslSocket: cannot resolve CRYPTO_free
W QField  : (null):0 ((null)): qt.network.ssl: QSslSocket: cannot resolve EVP_rc2_cbc
W QField  : (null):0 ((null)): qt.network.ssl: QSslSocket: cannot resolve SSLv2_client_method
W QField  : (null):0 ((null)): qt.network.ssl: QSslSocket: cannot resolve SSLv2_server_method
W QField  : (null):0 ((null)): qt.network.ssl: QSslSocket: cannot resolve EC_get_builtin_curves
W QField  : (null):0 ((null)): qt.network.ssl: QSslSocket: cannot resolve EC_curve_nist2nid
W QField  : (null):0 ((null)): qt.network.ssl: QSslSocket: cannot call unresolved function EC_get_builtin_curves
W QField  : (null):0 ((null)): qt.network.ssl: QSslSocket: cannot call unresolved function EC_get_builtin_curves
```
