### ISSUE TITLE
Enhancement : Keep the expression for visibility (form)

### ISSUE THREAD

**Issue by Ipickedausername** [opengisch/QField#2406]
Hello, 

When using expressions to control the visibility of containers (in attributes form) , the expression is working when we add a new entity, but all containers are shown when modifying the entity. 

For example, when creating the new entity, if "field 1" = 'X' , container 1 is shown. However, when modifying this entity, "field 1" stays as = 'X', and all the other containers are still visible.

I think, just like QGIS, QFIELD should check if the expression is valid when we chose to modify the entity and then show the right container. 

QField version: [1.10.0 (1da006 v1.10/0)]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by nirvn** [comment]
@Ipickedausername , could you add a small test project here that replicate this? It'll drastically increase the chance of a developer looking at it.

**Comment by Ipickedausername** [comment]
Hello, 

Here a small test project as asked. 
One folder for QGIS the other for QFIELD. 

On QFIELD, add a new point on "SAISIE_PT" layer and, on the first field (value list), choose one of the proposed items (ex "Flore").
A new containter will be shown. Complete the constraints if asked. 

Open the entity for modifications. Then you can see all the containers are now shown, and we can fill or modify all the fields. 

Than you for your attention. 

Have a good day ! 
[Test_visibility_cont_QFIELD.zip](https://github.com/opengisch/QField/files/7876965/Test_visibility_cont_QFIELD.zip)
[Test_visibility_QGIS.zip](https://github.com/opengisch/QField/files/7876966/Test_visibility_QGIS.zip)

**Comment by suricactus** [comment]
@Ipickedausername can you test the latest master or the apks in PR #2409 ? All should be good now.

**Comment by Ipickedausername** [comment]
Hello, 

It seems to not working not totaly well. 

When adding a new entity, if I try to modify it right away, all containers are shown.
But, if I close and reoppen the project, then only the good container is shown. 
It also works if I move the entity before modifying fields. 

I added a little video to show it. 

Thank you !

https://user-images.githubusercontent.com/72577399/149662917-cfd853f1-f985-4d59-8b76-fdeb52ad887c.mp4

**Comment by suricactus** [comment]
Confirmed. This issue is different from what I have fixed in #2409 . Will have a look .

**Comment by suricactus** [comment]
Hey, @Ipickedausername I checked you project. Seems the problem is only for the painfully long visiblity expressions... Unfortunately they are barely readable for me as I am not involved in the project. Can you reproduce the issue with event simpler experessions? What I have seen is that you depend on values with accents such as `Sondages pédologiques`, `Sécurité` and `Accès`. Can you check if the project works properly if you don't use values and expessions with accents?

**Comment by Ipickedausername** [comment]
Hello, 

I changed my project so now the visiblity expression depends on an ID related on the selection. 
Ex: Sondages pédologiques = 2 ; Sécurité = 15 and Accès = 13. 

I still have the same issue. I have to move the entity to make sure the visibility expression is well applied. 
Here another video. 

https://user-images.githubusercontent.com/72577399/150088355-3ed04dd4-69f3-46da-a207-6e0dbee40761.mp4

Or maybe there is something I don't understand. 
Thank you. 

Have a good day !

**Comment by suricactus** [comment]
@Ipickedausername can you please provide the new project here? And if possible, reduce the visibility expression to the minimal example that does not work properly. Checking a 2500 character expression is not an easy task. Providing a simple test project dramatically increases the chances a developer looking at your issue.

**Comment by suricactus** [comment]
Well, it turns out the expression was way too exclusive. For example if I fill in a "Reptile", I have to fill in the value for `code_esp`. When I change the value to something "Divers", the expression depends on the value `code_esp` which is still there because of the "Reptile". So it seems the problem is in the expression, not how QField handles it.

Also from the screencast it seems you are not using the latest master (black buttons in the top bar).

![Peek 2022-01-19 12-22](https://user-images.githubusercontent.com/2820439/150111837-ba858afd-72c4-4c8b-a441-9a6b7751a60a.gif)

Closing now, I am not convinced there is an error on the QField side.

**Comment by Ipickedausername** [comment]
Hello, 

> For example if I fill in a "Reptile", I have to fill in the value for `code_esp`. When I change the value to something "Divers", the expression depends on the value `code_esp` which is still there because of the "Reptile".

Yes I made this on purpose. When we change the compartment, we have to make sure every crucial field is empty or completed. 

I'm probably not using the lastest master (downloaded 3 days ago). As your screencast shows, everything seems working well on the latest version.  

Thank you !
