### ISSUE TITLE
QField freeze when changing legend display

### ISSUE THREAD

**Issue by Ipickedausername** [opengisch/QField#2973]
Hello,

I'm using a specific field in "Options" to change the theme of the layer. 
I've been forced to proceed this way because the "Theme system" proposed on QGIS is very unpractical (for example: every change on the attribute form isn't saved to all the theme ; and it is not practical to manage and update). 

In order to change the legend of my layer "DATA_PT", I'm using a field "Point_shap" on another layer ('OPTIONS'). 
In the layer 'DATA_PT' the symbology of the size and color of the point depends on the value in "Point_shap". 
If "Point_shap" = "Points" ; it is using points, if it is "Circles", it is using circles. 

Everything is working well on QGIS (and quite fast), on QField I didn't notice any problem, except when I change the value of "Point_Shap". When I do so, the map is freezing. No zoom, no move. I still can select entities and open the options' menu. If I choose to zoom on my layer, the freeze disappear and the right legend is applied to the layer. 

I attach a video of the issue. 

https://user-images.githubusercontent.com/72577399/173174367-d97754ef-6935-424a-9ef2-1f15314af28a.mp4

When I have a moment, I'll try to create an "example project". 

Desktop (please complete the following information)

    OS: [e.g. Windows 10]
    QGIS Version [e.g. 3.24.3]
    QFieldSync Version [e.g.4.1.1]

Mobile (please complete the following information)

    Device: [Samsung Galaxy S9]
    OS: [e.g. Android 10]
    QField version: [Qfield master-dev (9d07df)]

Additional information

    Problem started happening recently, didn't happen in an older version of QField: [No]
    Problem can be reliably reproduced, doesn't happen randomly: [Yes]
    Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by nirvn** [comment]
Interesting issue. A test project would be most needed here.

**Comment by nirvn** [comment]
@lindacamathias , you can try APKs in this PR (https://github.com/opengisch/QField/pull/2976), your problem should be fixed.

**Comment by nirvn** [comment]
@Ipickedausername , oups, pinged the wrong user earlier :) give the APKs I mentioned above a try, your issue should be fixed.

**Comment by Ipickedausername** [comment]
Hi, 
This issue isn't solved. I was working on my expressions to check if I did a mistake. I made some changes, but for now everything behaves the same. 

I'll create a project to give a better example.

**Comment by nirvn** [comment]
@Ipickedausername , have you tried the APKs?

**Comment by Ipickedausername** [comment]
I downloaded the update via Play Store.     
QField master-dev ab1120

**Comment by nirvn** [comment]
@Ipickedausername , that's not recent enough :) the fix was merged into master less than an hour ago. It should be on the play store within the next 12 hours.

**Comment by Ipickedausername** [comment]
Ah alright. I'll try to execute the APK (I'll search how.. ^^'). 

Also, I attach a simplified project, which do the same error (in case you would still need it). One is a QGIS version, the other is a QField export. 

[Test_QGIS.zip](https://github.com/opengisch/QField/files/8883736/Test_QGIS.zip)
[Test_QField.zip](https://github.com/opengisch/QField/files/8883735/Test_QField.zip)

**Comment by Ipickedausername** [comment]
I tested the APK, it is working well. Thank you !
