### ISSUE TITLE
Local Project with WFS layer fails to open on iPad 

### ISSUE THREAD

**Issue by JuanPufleau** [opengisch/QField#3981]
Local Project file with WFS layer fails to open on iPad 

To reproduce:

1. Create a simple QGIS project with one layer, the layer continents from the mapserver demo wfs
https://demo.mapserver.org/cgi-bin/wfs

         Or use attached project (or open attached layer definition in QGIS and add to your project).

2. Download to device, into the Imported projects folder.

3. Open local File / Imported projects.

4. QField crashes with no message and no log. Project doesn't open.

It works well in Android.  Even WFS-T works ok in Android.
Not using a project synched with QFieldCloud.

I'm using QGIS Version 3.22.10
QField Version 2.6.3  (aaa9ed v2.6.3) in both devices.
Android version 13.
iPad 9th generation software version 15.5

Have reproduced on 3 separate iPads.  With several WFS layers.

[ProjectOnlyWFSms.zip](https://github.com/opengisch/QField/files/10838570/ProjectOnlyWFSms.zip)

**Comment by m-kuhn** [comment]
Hi @JuanPufleau , thank you for reporting this. We have a potential fix ready, but we will need someone to confirm it.
Would you be able to send us your UDID, so we can add you to the tester list? https://udid.tech/

**Comment by JuanPufleau** [comment]
UDID:  00008110-000A71861147801E

Product / OS Version:  iPad14,2 / 19G82

**Comment by m-kuhn** [comment]
@JuanPufleau  Can you try to install the package from https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4029-aacf106e6efb19f0d67f5f5f68a9c17c488d7b8d.html ?

**Comment by JuanPufleau** [comment]
Sorry, can't install it.

Not sure if the problem comes from the package itself or from the fact that my organisation locks the iPads to only install App Store and App Catalog apps.

Message on the screenshot is:
Unable to install "QField Dev".  This app cannot be installed because its integrity could not be verified.

Maybe we'll need somebody else to test? 

![image](https://user-images.githubusercontent.com/45119838/225522798-43383462-a8aa-4ae3-8acf-f9c8abe7ea05.png)

**Comment by bradbrowne** [comment]
@m-kuhn I am also experiencing this issue and can validate this fix for you -- I will send my UDID to your email: matthias@opengis.ch

**Comment by bradbrowne** [comment]
Hi @m-kuhn, I am also getting the "the integrity could not be verified" message:

![IMG_1673](https://user-images.githubusercontent.com/79854/226501122-9887be20-abd0-4e1b-91cc-b056224a2be1.jpg)

Is it possible that the code signing certificate on your build server has expired?

**Comment by bradbrowne** [comment]
@m-kuhn I think there is sometimes an issue with the "Apple Developer ID Notary Service":

https://developer.apple.com/forums/thread/721443

Are you able to send me a link to a previous build that works that you have published via TestFlight so that I can install and then update to this latest version?

Failing that, it might work if you do the build again, and hopefully the "Apple Developer ID Notary Service" will correctly sign the package bundle.

**Comment by bradbrowne** [comment]
@JuanPufleau @m-kuhn Looking into this a bit more -- I think you might have to build again for our UDIDs to be registered with the app bundle:

https://stackoverflow.com/questions/72893647/ios-15-this-app-cannot-be-installed-because-its-integrity-could-not-be-verified

I think the 100 possible UDID values might be bundled with the executable somehow, and unless the build is signed after our UDID has been added to your profile, the integrity will not be able to be verified.

**Comment by m-kuhn** [comment]
Hi @bradbrowne yes, the app has to be built again to include the new UDID. I triggered another build now, does this install? https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4029-698d3790ccdaaa806e3fed23b638925e8fa7c3f3.html

**Comment by m-kuhn** [comment]
Yes, that's correct, the app needs to be rebuilt to include the new device.
An error has happened on our end, the device was added but not yet added to this profile. I just corrected this and it's being rebuilt at the moment. We should be ready for a new test in ~30 minutes.

**Comment by bradbrowne** [comment]
@m-kuhn thank you -- this new version worked!

**Comment by bradbrowne** [comment]
@m-kuhn this new version worked!  

Unfortunately QField is still crashing when opening local QGIS projects with WFS layer.

I have attached the simple QGIS project that I am using which only contains a single WFS layer:

[MapServer.zip](https://github.com/opengisch/QField/files/11027794/MapServer.zip)

Are you able to get crash reports from the TestFlight build?

**Comment by m-kuhn** [comment]
Here's a new version. This should be able to prove we are on the right track:
https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4029-2ae68d563144d5b178b330e0ad7ca092a9715a99.html

**Comment by bradbrowne** [comment]
@m-kuhn thank you -- I can successfully open QGIS projects with WFS layers now (at least the 2 examples I have).

Are there additional tests you would like me to run to confirm more scenarios?

**Comment by m-kuhn** [comment]
The next release of QField should have that fixed.
Thank you all for your help!
 @bradbrowne and @JuanPufleau you are one of the few users with access to ios builds for pull requests. You will find the link in the deploy step of the ios build action (if you are adventurous enough to click your way through github actions):
 
![image](https://user-images.githubusercontent.com/588407/227719455-631f8ba9-ebeb-4dd0-b136-b40ab215f448.png)

More testing of iOS functionality is much appreciated!
