### ISSUE TITLE
Attribute widget "attatchment": link to PDF

### ISSUE THREAD

**Issue by shapley** [opengisch/QField#4451]
### Describe the issue

I have linked a PDF in QGIS 3.22 LTS through the 'Attachment' widget and it opens as expected. If I then 'export' the directory and put it on an Android 10 phone the PDF shows but will not open the document and a 'blue' hyperlink isn't present.

### Reproduction steps

1. Set up a new form.
2. Add an 'Attachment' widget.
3. Export the directory with QField Sync Plugin
4. Place directory on Android Phone

### Expected behavior
A 'blue' hyperlink when pressed will open the PDF
### Observed behavior
The PDF name appears (without blue hyperlink) The layer is set as 'Directly access data source'

### Screenshots and GIFs
[If applicable, add screenshots and GIFs to help explain your problem.]

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
 - OS: Kubuntu 22.04 LTS
 - QGIS Version 3.22 LTS
 - QFieldSync Version [e.g.4.0.0]

### Mobile (please complete the following information)
 - Device: Samsung Galaxy 9
 - OS: Android 10
 - QField version:  2.8.3 Insightful Indri (256868)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

![qfield1](https://github.com/opengisch/QField/assets/7022885/3ef79b94-eaaf-46ca-b5c9-6f6c236a815e)
![qfield3](https://github.com/opengisch/QField/assets/7022885/0d04ddff-d074-44f8-9a3c-796b8476f742)
![qfield2](https://github.com/opengisch/QField/assets/7022885/18d2a4ff-56db-4a7d-9171-1221850553cd)
![qfield4](https://github.com/opengisch/QField/assets/7022885/78d7cd68-cbf9-4603-ba79-8634b8ceeeb6)
![qfield5](https://github.com/opengisch/QField/assets/7022885/ae3768a2-d3c5-4078-9f62-c9088efea90c)

**Comment by m-kuhn** [comment]
Can you change the type of 'integrated viewer"?

**Comment by shapley** [comment]
Changed it from 'Image' to 'Web View' then as shown but still doesn't create a  link

**Comment by shapley** [comment]
Changed it from 'Image' to 'Web View' then as shown but still doesn't create a  link

**Comment by shapley** [comment]
Changed it from 'Image' to 'Web View' then as shown but still doesn't create a  link

**Comment by shapley** [comment]
Changed it from 'Image' to 'Web View' then as shown but still doesn't create a  link

**Comment by shapley** [comment]
Changed it from 'Image' to 'Web View' then as shown but still doesn't create a  link

**Comment by shapley** [comment]
Changed it from 'Image' to 'Web View' then as shown but still doesn't create a  link

**Comment by shapley** [comment]
Changed it from 'Image' to 'Web View' then as shown but still doesn't create a  link

**Comment by shapley** [comment]
Changed it from 'Image' to 'Web View' then as shown but still doesn't create a  link

**Comment by shapley** [comment]
Changed it from 'Image' to 'Web View' then as shown but still doesn't create a  link

**Comment by shapley** [comment]
Changed it from 'Image' to 'Web View' then as shown but still doesn't create a  link

**Comment by shapley** [comment]
Changed it from 'Image' to 'Web View' then as shown but still doesn't create a  link

**Comment by shapley** [comment]
Changed it from 'Image' to 'Web View' then as shown but still doesn't create a  link

**Comment by shapley** [comment]
Changed it from 'Image' to 'Web View' then as shown but still doesn't create a  link

**Comment by shapley** [comment]
Changed it from 'Image' to 'Web View' then as shown but still doesn't create a  link

**Comment by shapley** [comment]
Changed it from 'Image' to 'Web View' then as shown but still doesn't create a  link

**Comment by shapley** [comment]
Changed it from 'Image' to 'Web View' then as shown but still doesn't create a  link

**Comment by shapley** [comment]
Changed it from 'Image' to 'Web View' then as shown but still doesn't create a  link

**Comment by shapley** [comment]
As above but forgot the image attachment

**Comment by shapley** [comment]
As above but forgot the image attachment

**Comment by shapley** [comment]
As above but forgot the image attachment

**Comment by shapley** [comment]
As above but forgot the image attachment

**Comment by shapley** [comment]
As above but forgot the image attachment

**Comment by shapley** [comment]
As above but forgot the image attachment

**Comment by shapley** [comment]
As above but forgot the image attachment

**Comment by shapley** [comment]
As above but forgot the image attachment

**Comment by shapley** [comment]
As above but forgot the image attachment

**Comment by shapley** [comment]
As above but forgot the image attachment

**Comment by shapley** [comment]
As above but forgot the image attachment

**Comment by shapley** [comment]
As above but forgot the image attachment

**Comment by shapley** [comment]
As above but forgot the image attachment

**Comment by shapley** [comment]
As above but forgot the image attachment

**Comment by shapley** [comment]
As above but forgot the image attachment

**Comment by shapley** [comment]
As above but forgot the image attachment

**Comment by shapley** [comment]
Sorry...github rejecting image attachment.

**Comment by shapley** [comment]
Sorry...github rejecting image attachment.

**Comment by shapley** [comment]
Sorry...github rejecting image attachment.

**Comment by shapley** [comment]
Sorry...github rejecting image attachment.

**Comment by shapley** [comment]
Sorry...github rejecting image attachment.

**Comment by shapley** [comment]
Sorry...github rejecting image attachment.

**Comment by shapley** [comment]
Sorry...github rejecting image attachment.

**Comment by shapley** [comment]
Sorry...github rejecting image attachment.

**Comment by shapley** [comment]
Sorry...github rejecting image attachment.

**Comment by shapley** [comment]
Sorry...github rejecting image attachment.

**Comment by shapley** [comment]
Sorry...github rejecting image attachment.

**Comment by shapley** [comment]
Sorry...github rejecting image attachment.

**Comment by shapley** [comment]
Sorry...github rejecting image attachment.

**Comment by shapley** [comment]
Sorry...github rejecting image attachment.

**Comment by shapley** [comment]
Sorry...github rejecting image attachment.

**Comment by shapley** [comment]
Sorry...github rejecting image attachment.

**Comment by shapley** [comment]
Sorry...github rejecting image attachment.

**Comment by shapley** [comment]
Sorry...github rejecting image attachment.

**Comment by shapley** [comment]
Sorry...github rejecting image attachment.

**Comment by shapley** [comment]
Sorry...github rejecting image attachment.

**Comment by shapley** [comment]
Sorry...github rejecting image attachment.

**Comment by 9ls1** [comment]
Not sure if this i the same "issue" that I ran into. However, just in case, here's a link to my solution for including a default pdf-file to a QGIS-form to be used in QField: [https://gis.stackexchange.com/questions/349656/how-to-include-a-pdf-for-displaying-or-downloading-in-qfield/464414#464414](url)

**Comment by shapley** [comment]
For the record here it is:-
https://gis.stackexchange.com/questions/349656/how-to-include-a-pdf-for-displaying-or-downloading-in-qfield

**Comment by 9ls1** [comment]
@shapley Sorry, my mistake in pasting the url, should work now.

**Comment by shapley** [comment]
Tried this suggestion but I now have a different issue... I have had to change from a *.pdf to a *.docx but still the same issue... it works perfectly in QGIS (and i'm just using 'Package for QField' only then transferring the 'export' directory to phone with attachment directory included).  Thank you for your time 9ls1

![layer-properties](https://github.com/opengisch/QField/assets/7022885/ecaa71f2-6f77-4e48-a304-e461b90caddf)

**Comment by 9ls1** [comment]
@shapely Have you tried **without** including /Docs in the "Default **path**", only have it included in the "Default **value**". (I have assumed the default path to be the project folder). I presume you have Docs included as an Attachment directory.

**Comment by 9ls1** [comment]
@shapley I just added a Word document in the pdf-subfolder in the default project-folder and set the default value to 'pdf/test.docx' in the form and created a cloud project: The Word-file can be clicked and opened in QField. Just be sure the pdf-folder (the Docs-folder in your case) is only added in the Default value (and not in the Default path further up).

**Comment by shapley** [comment]
I'll give that a try.

**Comment by shapley** [comment]
Many thanks to '9ls1' for thier patience.
