### ISSUE TITLE
QField Offline layer is empty

### ISSUE THREAD

**Issue by Oisin-JK** [opengisch/QField#4695]
I have a QGIS project, with multiple layers. Some are shape (.shp) files, others are geopackage (.gpkg) files.

I am having problems with one of the layers in a geopackage called 'trees.gpkg'. The geopackage contains two layers: 'tree-pt' and 'tree-ar', containing approximately 2500 and 200 features respectively . 

I am packaging using QFieldSync for cable export. Cable layer action for both layers is set to offline editing. However, in the packaged QField project, the layer 'tree-pt' is empty. All source files and QField project are on local (not network) drives.

If I set the 'Cable layer action' action for 'tree-pt' to  copy, it is not empty. 

If I create two geopackages, one for each layer, and for each set 'Cable layer action' to 'offline editing', neither is empty. This is a  workaround solution that I will use, but I suspect this is a bug and hence why I have posted the issue.

Although I have encountered this issue on other projects, it does not occur for all projects and I cannot reliably recreate the issue. For this particular project, I have tried creating a new project using the same layers but the problem persists. In this same project I have another geopackage called 'relations.gpkg' that contains three non-spatial tables. These are also set to 'offline editing' and all package successfuly for QFIeld.  

To be clear, the issue seems to be that for a particular geopackage file containing two (or more?) layers, when using 'offline editing' one layer does not package correctly and is empty in the QField Project.

**Software**
 - OS: Windows10
 - QGIS Version 3.28.11
 - QFieldSync Version 4.6.0

Unfortunately, I cannot share the project publicly.

Any suggestions welcomed.

**Comment by Oisin-JK** [comment]
A further update. 

I recreated the project again....I created separate geopackages for the spatial layers 'treePt' and 'treeAr'. These now work. 

I reused the geopackage containing three non-spatial related tables. These now package as empty.

This does seems like a bug.

**Comment by nirvn** [comment]
@Oisin-JK , without access to a sample dataset to replicate the issue here, it'll be difficult to fix it. Try to come up with a small sample project you can share.

**Comment by Oisin-JK** [comment]
Hi Mathieu
I could share the full project with you, but just not on a public forum. Is that possible?

**Comment by ckpusitaro** [comment]
we have similar error, maybe @nirvn can check my project in qfieldcloud community project.
project name "KRK-KKPR"
username "ckpu-sitaro"
broken layer name "Polaruang_Sitaro"

**Comment by nirvn** [comment]
I *think* this should be fixed with qfieldsync 4.9.0.

**Comment by ckpusitaro** [comment]
have been using the 4.9.0, the problem still, no feature shown

**Comment by nirvn** [comment]
@ckpusitaro , can you try to change the packaging offliner to "optimized packager" in your cloud project settings (on app.qfield.cloud):

![image](https://github.com/opengisch/QField/assets/1728657/541de300-f0b9-4473-a924-1288bcd23b8b)

**Comment by ckpusitaro** [comment]
Thanks @nirvn Works like a charm!

**Comment by julienrobvq** [comment]
@Oisin-JK 

I have been experiencing similar issues with cable export. Features in one of my gpkg have been disapearing when packaging. In my case, the gpkg only contains one layer. 

I was wondering if you ended up fixing the problem without having to create multiple gpkg or setting the action to copy. 

@nirvn 

If no solution has been found, I could share a projet in which the problem has occured. Has the issue been resolved for cable export ? 

Thanks !
