### ISSUE TITLE
"Wrong" error message shown when using localized data sources with QField Cloud

### ISSUE THREAD

**Issue by jguelat** [opengisch/QField#4956]
### Describe the issue
An error message saying the project was not correctly packaged is shown after downloading a project that is using a localized data source.

### Reproduction steps
1. Create a new project in QGIS using a vector layer and a localized data source (I used a raster background map).
2. Upload the project to QField Cloud using QFieldSync, no problem (only the vector layer and the project file are uploaded).
3. On the tablet, copy the localized raster dataset in the QField/basemaps folder.
4. On the tablet, download the project from QField Cloud.
5. You get the error message.

### Expected behavior
The error message should not be shown since the project can be opened properly on the tablet (it looks like QField Cloud now supports localized data sources, yeah!).

### Observed behavior
A big (scary :D) warning is shown after downloading the project on the tablet saying that QField Cloud had troubles packaging my project.

### Desktop (please complete the following information)
 - OS: Windows 10 Pro
 - QGIS 3.34.2
 - QFieldSync Version 4.6.4

### Mobile (please complete the following information)
 - Device: Galaxy Tab Active3
 - OS: Android 11
 - QField version: 3.1.8 (142367)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: localized data sources were not working at all with QField Cloud with previous versions
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Only with localized data sources

QField Cloud username: jguelat
QField Cloud project: testproj_localized

**Comment by suricactus** [comment]
@jguelat, your report is just in time to test the PR I pushed yesterday: https://github.com/opengisch/QField/pull/4951#issuecomment-1891008613 . Can you please confirm the misleading message is now gone for your project?

**Comment by jguelat** [comment]
Hi! Thanks for your help! I've just tested the apk and it doesn't seem to work properly. I still get the warning message and moreover the localized raster is not shown at all.

Sorry for the bad news...

**Comment by suricactus** [comment]
Yup, all is good. This apk and the next release of QFieldCloud will make it work as intended. Will ask you to check again these weeks. :)
