### ISSUE TITLE
Many-to-many field behaviour inconsistent with QGIS

### ISSUE THREAD

**Issue by agseaton** [opengisch/QField#5180]
### Describe the issue
The behaviour in QField of many to many fields is not consistent with that in QGIS.

In the QGIS attribute form configuration, a many-to-many field can be configured to allow the user to add, delete, link, or unlink items in the target table.

![Screenshot from 2024-04-11 16-00-08](https://github.com/opengisch/QField/assets/1802137/122297e4-693c-484e-9e67-adda9277bc9a)

However, the link and unlink options don't work in QField -- the field is blank and can't be edited.

Additionally, while the add and delete options work in QField, and they actually function as 'link' and 'unlink' do in QGIS, i.e. they don't actually allow creation and deletion of rows in the target table.

### Reproduction steps

1. Set up two tables and a join table
2. Configure QGIS relations for a many-to-many relationship between the two tables
3. Set up attribute form for the relation with either 'link' and 'unlink' selected, or 'add' and 'delete'.
4. Export to QField
5. Test form in QField.

### Expected behavior

**If link and unlink are selected:**
![Screenshot from 2024-04-11 16-00-08](https://github.com/opengisch/QField/assets/1802137/122297e4-693c-484e-9e67-adda9277bc9a)

Form should allow linking/unlinking an existing child feature, as shown in QGIS:
![Screenshot from 2024-04-11 16-10-45](https://github.com/opengisch/QField/assets/1802137/f59d596b-ae52-43b3-a35a-98985663e82c)

![Screenshot from 2024-04-11 16-06-55](https://github.com/opengisch/QField/assets/1802137/8784c9fe-bcc3-4eeb-b3c0-934bfd8ccb7b)

**If add and delete are selected:**
![Screenshot from 2024-04-11 16-15-14](https://github.com/opengisch/QField/assets/1802137/c350fc74-8b33-46b5-8493-36e6937d21f5)

Form should allow adding new features/deleting existing ones from the child table, again demonstrated in QGIS:
![Screenshot from 2024-04-11 16-12-44](https://github.com/opengisch/QField/assets/1802137/5ae960c1-2298-42e4-9ab8-9747db6eab32)

![Screenshot from 2024-04-11 16-13-59](https://github.com/opengisch/QField/assets/1802137/8826a9a2-1392-40f0-9527-62bb1d11c550)

### Observed behavior

**If link and unlink are selected:**
QField widget doesn't do anything

![Screenshot from 2024-04-11 16-15-52](https://github.com/opengisch/QField/assets/1802137/916db9bf-79b3-4df0-960b-badb1fb706f4)

**If add and delete are selected:**
QField widget is functional, but actually just allows linking and unlinking, not adding and deleting:

![Screenshot from 2024-04-11 16-19-17](https://github.com/opengisch/QField/assets/1802137/77949990-2146-4964-8e3f-2c22fca0a8bd)

![image](https://github.com/opengisch/QField/assets/1802137/b4940a20-c77c-4fe1-a3c0-795199684f03)

![Screenshot from 2024-04-11 16-19-46](https://github.com/opengisch/QField/assets/1802137/b8bada5e-a5f5-4099-847f-5a7d9f0134d7)

Note here also that QField displays the attributes form for the join table, whereas QGIS bypasses that entirely (which is the desired behaviour).

### Sample project file & database

[m2m.zip](https://github.com/opengisch/QField/files/14951898/m2m.zip)

### Desktop (please complete the following information)
 - OS: Ubuntu 22.04.4 LTS
 - QGIS Version 3.34.5-Prizren
 - QFieldSync Version v4.9.1

### Mobile (please complete the following information)
 - Device: Oneplus 11
 - OS: Android 14
 - QField version: 3.2.2 - Congo 72be17

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Tested with GPKG and spatialite.

**Comment by nirvn** [comment]
@agseaton , have you tried with the latest QField 3.3 version? A couple of bugs were fixed with relations with cardinal configuration.

**Comment by agseaton** [comment]
Sorry for not getting back to you earlier on this.

I've tested it out with the example project provided above and QField 3.4, and I'm still seeing the issues I described.

**Comment by nirvn** [comment]
@agseaton , this has been fixed in QField 4.0 or 4.1. Happy field mapping :)
