### ISSUE TITLE
delimiter bug

### ISSUE THREAD

**Issue by jarvojta** [opengisch/QField#554]
We discovered a issue with decimal delimiters in the recent updates. Today I found it even in the most recent update (1.0.3 - Matternhorn (10003993)). I have several fields  where a decimals should be inserted by user. It worked perfectly depending on the device settings. That means users with global language set to English  were able to use dot "." as decimal delimiter and users with Czech language used comma "," as a delimiter. Nothing else was allowed by the app.
Now comes the bug in the new versions which I will describe for English setting. Currently, both dot and comma are seemingly allowed for input by the application. However, when the user inputs comma, the number will be stored as a whole number (e.g. 15 instead of 1.5).

**Comment by 3nids** [comment]
isn't this because the coma is considered as a thousand delimiter?

**Comment by jarvojta** [comment]
Yes, you are right. It was my mistake that it happens on devices with Czech settings. However, I find it still confusing. The user could wrongly expect comma as delimiter and will input terribly wrong data when working on device with language set to English but with form in any language language with "," as decimal delimiter) . The English user can accidentally input wrong number as well, although it is less probable. 1,5 could be meant as 15, 1.5 or 1,500 but Qfield writes 15 without warning. 
It would be nice if QField would not accept anything else than numbers with exactly 3 digits after comma when the language is set to English. Another great improvement would be that one can set the right number format for the project independently on the device settings.

**Comment by phardy-egis** [comment]
We noticed this bug as well, I can provide detail if required. Has it been fixed yet ? Waiting for a fix, is there a good practice to follow in order to avoid this bug ?

**Comment by 9m-andre** [comment]
Hello, we also have this problem in french QField : we cannot input a decimal number. We only have . and - in the numeric pad and 1.5 become 15. ... Not really useful to enter surfaces.

**Comment by nirvn** [comment]
@9m-andre , @jarvojta , are things better in QField 3.5? We fixed an issue on that front a while back.

**Comment by paul-carteron** [comment]
Hi @nirvn,

Some feedback on the latest version: the issue still occurs on the French version of QField.

Below is an example. When I enter a value using a comma as the decimal separator (e.g. 1,2), after saving the comma is removed and the value is converted to an integer (1,2 → 12).

I tested this on multiple versions : dev, 4.0.6, 3.7.9, and 3.5.0. The issue is present in all of them.

<p align="center">
  <img src="https://github.com/user-attachments/assets/14373138-e9cc-433f-9d01-f2e4688570d0" width="45%" />
  <img src="https://github.com/user-attachments/assets/c7d5e6f1-a868-4ee5-a10b-604a22d82a8f" width="45%" />
</p>

As you can see below, my local is set to french :

<p align="center">
    <img src="https://github.com/user-attachments/assets/8825f11d-61b9-42f3-972e-c12c50e5a352" width="45%" />
</p>

If that can help, here also my QGIS form setup :

<img width="573" height="422" alt="Image" src="https://github.com/user-attachments/assets/cfa6572d-6b7e-47da-acea-935eede8b74c" />

**Comment by ea-eriksson** [comment]
Hi, I noticed that in: /src/qml/editorwidgets/Range.qml a DoubleValidator with locale: 'C' is used.
```
  DoubleValidator {
    id: doubleValidator

    locale: 'C'

    bottom: rangeItem.min
    top: rangeItem.max
    decimals: isDouble ? -1 : 0
  } 

```

No matter what locale settings a user runs with, this validator treats commas as thousand delimiter (and we also have decimal point).

Perhaps it could have been set like `locale: Qt.locale()`, but, maybe this results in other problems. Alternatively, if commas would not be accepted as thousands delimitors, and thus not a possible input, then it would be easier for users as well.
