### ISSUE TITLE
auto filter of drop down values

### ISSUE THREAD

**Issue by elmonchas** [opengisch/QField#5682]
### Describe the issue
recently the auto filter of drop down values does not work anymore. I noticed this issue in 3.4.1 Ebo. 

Previously the number of options to choose from would get filtered while typing. The new behaviour is that after typing you need to press enter to filter the list of possible options. 

### Reproduction steps
make a value relation widget and filter the list typing. No values get filtered, unless you press enter 

### Expected behavior
It would be much faster if values get filtered while typing (this was the old behaviour!)

### Observed behavior
pressing enter is nessecary to filter the value relations

### QField (please complete the following information)
Issue is present in 3.4.1. ebu. In Darien it was not present.

**Comment by nirvn** [comment]
@elmonchas , can you provide a sample project?

**Comment by elmonchas** [comment]
[sample project.zip](https://github.com/user-attachments/files/17160065/sample.project.zip)

yes, I have attached the qfield project folder. Try to add a point on layer "soort_ilp2425_v2". 

The issue happens on samsung galaxy tab (android 13)

**Comment by nirvn** [comment]
@elmonchas , thanks -- I can't replicate, but I'm pretty sure this is a samsung virtual keyboard behavior.

The PR here (https://github.com/opengisch/QField/pull/5695) should fix it. In 10 minutes or so, APKs will appear, could you test and report back whether this is fixed? Thanks.

**Comment by elmonchas** [comment]
@nirvn I have finally been able to test this fix.
unfortunately this does not solve the specific issue. it actually made a worse behaviour:

new behaviour: while typing the list does not filter and after pressing enter only the virtual keyboard disappears.

**Comment by elmonchas** [comment]
I did a bit more testing. I still had version 5359 (https://github.com/opengisch/QField/pull/5364) installed.

Here the autofilter works normal on my device.

**Comment by elmonchas** [comment]
Thanks a lot! this APK worked out! :)

**Comment by nirvn** [comment]
@elmonchas , thanks
