### ISSUE TITLE
Simple constraint prohibits the record

### ISSUE THREAD

**Issue by Emic37** [opengisch/QField#580]
I encountered opposite issue than the issue #301. So, I set a simple constraint with expression and Qfield prohibits the records of the entity.

### Expected behavior:

Same behavior of Qgis.

### Observed behavior:

I set the constraint as described in the picture :
![constraint_qgis](https://user-images.githubusercontent.com/2921424/58160323-845e3200-7c7e-11e9-9b17-414363884feb.JPG)

In Qgis, all works perfetly. I can save the entity even if the constraint is not respected. But in Qfield, impossible to save the entity. Qfield displays `Constraints not valid` and the only way to close the entity is to cancel the changes : 

![Screenshot_20190519-082049_QField](https://user-images.githubusercontent.com/2921424/58161259-36e2c480-7c80-11e9-8814-e3c84b79ec55.jpg)

**QField version:** [1.0.4]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [I don't know]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [No tested]

**Comment by gioman** [comment]
> Problem started happening recently, didn't happen in an older version of QField: [I don't know]

@Emic37 
I don't think that at the time you posted this the problem was recent. I tested as back as https://github.com/opengisch/QField/releases/tag/release-0.11.11 and I can still see this. 

@mbernasocchi not sure this wasn't an issue in the past or just never worked in qfield as it does in qgis.

**Comment by saemiw** [comment]
still an issue with qfield 1.2.0. Even if "enforce expression constraint" is not checked it is enforced. In this way QField behaves differently to QGIS 3.4.12

**Comment by BoswachterMarc** [comment]
I was looking for a solution about this problem and came along Github.
It looks like the problems starts in QGIS (version 3.4.6-Madeira)? When trying to add constraints for some widgets, and triggering them one for one, each time the values are changing...
- Expression "Type" = 15 changes to Indien gevaarlijke boom
- Expression description Indien gevaarlijke boom changes to "Type" = 15

I closed QGIS and restarted it but this was no solution.
QField behavior is behaving in the same way (some constraints are ok, others not). Every time I make a new package for QField I have some constraints fields that are working and others don't...

![Knipsel3](https://user-images.githubusercontent.com/57868975/69010121-80287e00-095c-11ea-96bd-449c29d839c5.PNG)
![Knipsel2](https://user-images.githubusercontent.com/57868975/69010122-80287e00-095c-11ea-9663-0e89486d53db.PNG)
![Knipsel3](https://user-images.githubusercontent.com/57868975/69010123-83bc0500-095c-11ea-8719-f74546bf14ca.PNG)
![Knipsel2](https://user-images.githubusercontent.com/57868975/69010124-83bc0500-095c-11ea-8cbb-bbcaf2cb2dd8.PNG)

Regards,
Marc

**Comment by nirvn** [comment]
@BoswachterMarc , there's been loads of improvements on that front, are you still seeing this issue with the latest release?

**Comment by gioman** [comment]
>  are you still seeing this issue with the latest release?

@nirvn just had a look, it is fixed to me.

**Comment by nirvn** [comment]
Great.

**Comment by Tarandeep97** [comment]
I am still facing same issue, can anyone help how you fixed it?

**Comment by nirvn** [comment]
@Tarandeep97 , are you using QField's latest publicly available version (2.2.3)? If the answer is yes and you still face an issue, you're likely going to increase the chances of a dev looking at this by attaching a sample project with clear steps to reproduce what you think is wrong.
