### ISSUE TITLE
new regression in value relation form

### ISSUE THREAD

**Issue by elmonchas** [opengisch/QField#6584]
### What is the bug or the crash? What were your expectations and what actually happened?

In the new version (3.7.4) there are some new regressions in the value - relation form  behaviour.

1. In the feature form it shows the value (code)  and not the relation. When editing a value- relation, the dropdownmenu works fine and you can see and select the relation value.  After saving the update and going back to the feature form, it shows the value (code)  again.

screenshot:
abundantie is filled in here with value relation (6-25)
ndff_nr is also a value relation. It shows the value (code)  and not the relation (species name)
![Image](https://github.com/user-attachments/assets/5f939b28-64ad-48f8-8176-fb3a6877bceb)

screenshot:
after saving and reopening the form see field abundantie changed from "6-25" to the underlaying value (3)

![Image](https://github.com/user-attachments/assets/2098f35a-083d-4d12-9537-1aa889616ccf)

2. the previous selected value (relation) copies to the next new feature (pin to copy is turned off).  Strangly, it shows in the new feature, but is actually null (see screenshot. abundantie shows 6-25, but does not not pass not null constrain).

screenshot:
this is the form when adding another new feature. Notice field abundantie remembers the previous value of "6-25" but the real value is actually NULL (as it should be).  The field does not pass NULL constrain

![Image](https://github.com/user-attachments/assets/a7ade876-6de6-4771-840a-7bbe95cc35ae)

3. The buggy behaviour from point 2 also applies when selecting multiple features, editings one and moving to the next one.

  

### Steps to reproduce the issue

make a value relation. fill in the field, save changes and re-open the attribute form.  The value -relation has changed.
Add a new feature. The relation value is already filled in, but the real value for this field is NULL.

### Version

version 3.7.4 

### Operating system name

Android

### Operating system version

android version 13. samsung galaxy tab active 3

### Reinstall QField

- [x] I have a fresh install of the latest QField version, but the problem persists.
- [x] Problem can be reliably reproduced, doesn't happen randomly.
- [x] Problem happens with all files and projects, not only some files or projects.

**Comment by nirvn** [comment]
@elmonchas , thanks, I'll look into this. FYI, we're planning to expand our test coverage with regards to this crucial editor widget. While 3.7 was a nice release, there were too many regressions on this front, we should do better.

**Comment by nirvn** [comment]
@elmonchas , could you provide a sample project? I can't replicate with a simple value relation configuration.

**Comment by elmonchas** [comment]
[sample_project.zip](https://github.com/user-attachments/files/21850995/sample_project.zip)

**Comment by nirvn** [comment]
@elmonchas , thanks, this should be fixed by this PR (https://github.com/opengisch/QField/pull/6585), you'll have some APKs to test in 10 minutes or so.

**Comment by elmonchas** [comment]
Thank you for  the quick fix. Unfortunately after installing the APK i just see a white screen similar to https://github.com/opengisch/QField/issues/6556

**Comment by elmonchas** [comment]
yesterday I cleared the cache and restarted the tablet, but I still get the white screen

**Comment by nirvn** [comment]
@elmonchas , apologies, the refreshed APK should now work here: https://github.com/opengisch/QField/pull/6585#issuecomment-3199844367

**Comment by elmonchas** [comment]
thanks. This updated APK works. The original issue is solved, but a new issue was introduced.

The order of the drop down menu got mixed up. 

screenshot of the wrong order:
![Image](https://github.com/user-attachments/assets/ec66ab4d-e86b-4a7f-9d45-bf0e986f713f)

screenshot of the original order in qgis:

![Image](https://github.com/user-attachments/assets/36b70dcb-3368-4888-b65e-675728b11c37)

I tested with another project and it had the same wrong order.  In dropdown lists with a filter (cascading dropdownmenu)  the order stayed good.

**Comment by nirvn** [comment]
@elmonchas , OK, another good finding, the newest APKs should fix this here: https://github.com/opengisch/QField/pull/6585#issuecomment-3199844367

**Comment by elmonchas** [comment]
Thank you once again. I tested the new APK and I am happy to confirm this one fixed everything!

Also good to hear your planning to extend test coverage for this editor widget. Indeed it is a very crucial one!
